### ISSUE TITLE
Is the dataset is available on LDC ?

### ISSUE THREAD

**Issue by apoorv001** [yuhaozhang/tacred-relation#1]
Hi Yuhao,

First of all, I would like to congratulate you on achieving the new state of the art results in the field using a completly novel technique.
Out of curiosity, I wanted to reproduce the results of the paper you published but could not find dataset for the same. I check the LDC website for new-corpora (https://www.ldc.upenn.edu/new-corpora) but could not find any reference to the dataset you mentioned.
It would be a great help if you could confirm if the dataset is present on LDC and if not what would be the tentative time for the same.

Cheers,
Apoorv

**Comment by yuhaozhang** [comment]
Hi Apoorv,

Thanks for your interest. Unfortunately at this moment we are still waiting for the final release of this dataset. You can subscribe to [this form](https://goo.gl/forms/nO70omzVyRNbDXt53), and I will send out notifications once we hear from LDC about the official release of this dataset.

Yuhao

**Comment by apoorv001** [comment]
Thanks Yuhao for the quick response. 
Regards, Apoorv 

Sent from Yahoo Mail on Android 
 
  On Thu, 11 Jan 2018 at 1:07 PM, Yuhao Zhang<notifications@github.com> wrote:   
Hi Apoorv,

Thanks for your interest. Unfortunately at this moment we are still waiting for the final release of this dataset. You can subscribe to this form, and I will send out notifications once we hear from LDC about the official release of this dataset.

Yuhao

**Comment by ni9elf** [comment]
Hi Yuhao,

Congratulations on the good work. Any update on the dataset availability on LDC?

Best,
Nigel

**Comment by yuhaozhang** [comment]
Sorry for this long delay! The dataset is now publicly available. Please find more information here: https://nlp.stanford.edu/projects/tacred/
