### ISSUE TITLE
Version of Stanford CoreNLP used for preprocessing TACRED

### ISSUE THREAD

**Issue by svjan5** [yuhaozhang/tacred-relation#16]
Hi,
I see that some information which is provided by Stanford CoreNLP is not included in the dataset. Can you tell me which version of CoreNLP was used for preprocessing it (3.8, 3.9, 4.0,....)? I want to run preprocessing once again without facing the tokenization mismatch problem.

Thanks in advance!

**Comment by yuhaozhang** [comment]
The original scripts used to produce CoreNLP annotations for TACRED were lost due to some internal server issue. But based on the time the annotations were produced, it is most likely that CoreNLP v3.7.0 was used (https://stanfordnlp.github.io/CoreNLP/history.html).

**Comment by svjan5** [comment]
Thanks a lot @yuhaozhang !
