### ISSUE TITLE
the result is bad

### ISSUE THREAD

**Issue by loveJasmine** [yuhaozhang/tacred-relation#2]
Evaluating on dev set...
Precision (micro): 100.000%
   Recall (micro): 0.000%
       F1 (micro): 0.000%
epoch 28: train_loss = 0.757685, dev_loss = 8.513657, dev_f1 = 0.0000
model saved to ./saved_models/00/checkpoint_epoch_28.pt

Evaluating on dev set...
Precision (micro): 100.000%
   Recall (micro): 0.000%
       F1 (micro): 0.000%
epoch 29: train_loss = 0.749475, dev_loss = 8.528827, dev_f1 = 0.0000
model saved to ./saved_models/00/checkpoint_epoch_29.pt

Evaluating on dev set...
Precision (micro): 100.000%
   Recall (micro): 0.000%
       F1 (micro): 0.000%
epoch 30: train_loss = 0.732781, dev_loss = 8.541955, dev_f1 = 0.0000
model saved to ./saved_models/00/checkpoint_epoch_30.pt

Training ended with 30 epochs.
$

**Comment by yuhaozhang** [comment]
Hi @loveJasmine, which data did you run the training on? Note that the data included in this repo is only a sample data with a few examples for debugging purpose, and you should not expect any meaningful results on this sample data.

**Comment by yuhaozhang** [comment]
Hi @loveJasmine, I am closing this issue if there is no further comment?
