### ISSUE TITLE
Confusion on micro metrics

### ISSUE THREAD

**Issue by TheShadow29** [yuhaozhang/tacred-relation#5]
I have a small confusion about the metrics. It seems you are using `micro` averaging for precision, recall and f1. I wanted to know if it makes sense to use `macro` averaging or not? To my knowledge `semeval` does use `macro` averaging. So I am wondering if there was any specific reason you chose to use `micro`.

**Comment by yuhaozhang** [comment]
There are mainly two considerations:

1. The [SemEval-2010 task 8](http://www.aclweb.org/anthology/S10-1006) dataset is created in a way that the distribution over different (positive) relations is roughly balanced, while [in the TACRED dataset different relations can have drastically different number of examples](https://nlp.stanford.edu/projects/tacred/#stats). The latter more closely reflects the distribution of relations in real-world text. In this case, using **macro** averaging can be misleading - a system can achieve high macro-F1 by simply doing well on a substantial number of rare relations while give completely wrong predictions on common relations, but a system like this won't achieve high micro-F1.

2. The TACRED dataset is created in the context of the yearly TAC Knowledge Base Population challenge, in which we often optimized our system for high micro-F1s.

**Comment by TheShadow29** [comment]
Thanks for the clarification
