### ISSUE TITLE
精度为1如何改代码？

### ISSUE THREAD

**Issue by liuzhencheng** [yuhaozhang/tacred-relation#6]
你好，请问一下，
Precision (micro): 100.000%
   Recall (micro): 0.000%
       F1 (micro): 0.000%

这种情况如何解决

**Comment by Wanying** [comment]
I think it is because the training dataset is too small. I checked the train.json, there are just 20 records there. We need to download the full TACRED dataset.

**Comment by yuhaozhang** [comment]
@Wanying is correct that this repo only contains a small sample of the dataset (see [this README](https://github.com/yuhaozhang/tacred-relation/blob/master/dataset/tacred/README.md)). If you want to reproduce the results on the TACRED dataset, you'll need to download the full dataset (more details on the [TACRED website](https://nlp.stanford.edu/projects/tacred/)).
